version: 1.0.{build}
build_script:
- cmd: nuget pack build-scripts.nuspec -version "{version}"
artifacts:
- path: '*.nupkg'
  name: nuget-package
deploy:
- provider: NuGet
  api_key:
    secure: qmYSE0Mpgzq09yBl+3xLWjHHc2LsGA3tYTpSq3WPHnOxW1cJ8TvOFPe7vrZjZ4Hh
  skip_symbols: true
  on:
    branch: master